In [55]:
%matplotlib inline
# import required libraries
import random
import datetime 
import numpy as np
import pandas as pd
from random import randrange

import matplotlib.pyplot as plt

import seaborn as sns

sns.set_style('whitegrid')
sns.set_context('talk')

params = {'legend.fontsize': 'small',
          'figure.figsize': (10, 5),
         'axes.labelsize': 'medium',
         'axes.titlesize':'medium',
         'xtick.labelsize':'medium',
         'ytick.labelsize':'medium'}

plt.rcParams.update(params)

from IPython.display import display, HTML

In [56]:

df = pd.read_csv('train_1.csv')
#hour_df = pd.read_csv('test_66516Ee.csv')
print("Shape of dataset::{}".format(df.shape))
#Shape of dataset::(79853, 13)


Shape of dataset::(79853, 18)


In [57]:
#df.drop(['id'], axis = 1, inplace = True)

In [58]:
df.head()

id  perc_premium_paid_by_cash_credit  age_in_days    Income  \
0  110936                             0.429     0.146599  0.003668   
1   41492                             0.010     0.463584  0.003226   
2   31300                             0.917     0.329447  0.000666   
3   19415                             0.049     0.256281  0.002510   
4   99379                             0.052     0.792797  0.001935   

   Count_3-6_months_late  Count_6-12_months_late  \
0                      0                       0   
1                      0                       0   
2                      2                       3   
3                      0                       0   
4                      0                       0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                               0                        0.891114   
1                               0                        1.000000   
2                               1                        0.849812   
3                               0                        0.959950   
4                               0                        0.997497   

   no_of_premiums_paid   premium  renewal  sourcing_channel_A  \
0             0.189655  0.035714        1                   0   
1             0.327586  0.285714        1                   1   
2             0.086207  0.035714        0                   0   
3             0.120690  0.142857        1                   1   
4             0.172414  0.142857        1                   0   

   sourcing_channel_B  sourcing_channel_C  sourcing_channel_D  \
0                   0                   1                   0   
1                   0                   0                   0   
2                   0                   1                   0   
3                   0                   0                   0   
4                   1                   0                   0   

   sourcing_channel_E  residence_area_type_Rural  residence_area_type_Urban  
0                   0                          0                          1  
1                   0                          0                          1  
2                   0                          1                          0  
3                   0                          0                          1  
4                   0                          0                          1

In [59]:
# get features and corresponding outcomes
feature_names = ['perc_premium_paid_by_cash_credit', 'age_in_days', 'Income',
       'Count_3-6_months_late', 'Count_6-12_months_late',
       'Count_more_than_12_months_late', 'application_underwriting_score',
       'no_of_premiums_paid', 'premium', 'sourcing_channel_A',
       'sourcing_channel_B', 'sourcing_channel_C', 'sourcing_channel_D',
       'sourcing_channel_E', 'residence_area_type_Rural',
       'residence_area_type_Urban']
training_features = df[feature_names]

outcome_name = ['renewal']
outcome_labels = df[outcome_name]

In [60]:
training_features.head()

perc_premium_paid_by_cash_credit  age_in_days    Income  \
0                             0.429     0.146599  0.003668   
1                             0.010     0.463584  0.003226   
2                             0.917     0.329447  0.000666   
3                             0.049     0.256281  0.002510   
4                             0.052     0.792797  0.001935   

   Count_3-6_months_late  Count_6-12_months_late  \
0                      0                       0   
1                      0                       0   
2                      2                       3   
3                      0                       0   
4                      0                       0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                               0                        0.891114   
1                               0                        1.000000   
2                               1                        0.849812   
3                               0                        0.959950   
4                               0                        0.997497   

   no_of_premiums_paid   premium  sourcing_channel_A  sourcing_channel_B  \
0             0.189655  0.035714                   0                   0   
1             0.327586  0.285714                   1                   0   
2             0.086207  0.035714                   0                   0   
3             0.120690  0.142857                   1                   0   
4             0.172414  0.142857                   0                   1   

   sourcing_channel_C  sourcing_channel_D  sourcing_channel_E  \
0                   1                   0                   0   
1                   0                   0                   0   
2                   1                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   residence_area_type_Rural  residence_area_type_Urban  
0                          0                          1  
1                          0                          1  
2                          1                          0  
3                          0                          1  
4                          0                          1

In [61]:
#df.info()

In [62]:
from sklearn.linear_model import LogisticRegression
import numpy as np

# fit the model
lr = LogisticRegression() 
model = lr.fit(training_features, np.array(outcome_labels['renewal']))
# view model parameters
model

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [80]:
from sklearn.ensemble import RandomForestClassifier
# fit the model
lr = RandomForestClassifier(max_depth=2, random_state=0) 
model = lr.fit(training_features, np.array(outcome_labels['renewal']))
# view model parameters
print(model.feature_importances_)
model

[0.14346794 0.0126084  0.00155495 0.18054255 0.36953277 0.22926759
 0.0188248  0.04020755 0.00352583 0.         0.         0.00046762
 0.         0.         0.         0.        ]


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=2, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [100]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(training_features, np.array(outcome_labels['renewal']),
                                                    train_size=0.8,
                                                    random_state=42)

/home/ubuntu/virtualenvironmentpython3/djangovijai/lib/python3.5/site-packages/sklearn/model_selection/_split.py:2026: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [114]:
lr = LogisticRegression()  
model = lr.fit(X_train, y_train)

In [115]:
print_score(model, X_train, y_train, X_test, y_test, train=True)

Train Result:

accuracy score: 0.9396

Classification Report: 
              precision    recall  f1-score   support

          0       0.56      0.12      0.20      3966
          1       0.94      0.99      0.97     59916

avg / total       0.92      0.94      0.92     63882


Confusion Matrix: 
 [[  482  3484]
 [  374 59542]]

Average Accuracy: 	 0.9396
Accuracy SD: 		 0.0011
train auc_roc 0.5576454792635055


In [116]:
print_score(model, X_train, y_train, X_test, y_test, train=False)

Test Result:

accuracy score: 0.9386

Classification Report: 
              precision    recall  f1-score   support

          0       0.61      0.14      0.23      1032
          1       0.94      0.99      0.97     14939

avg / total       0.92      0.94      0.92     15971


Confusion Matrix: 
 [[  145   887]
 [   94 14845]]

test auc_roc 0.5671058103989817


In [109]:
from sklearn.model_selection import cross_val_predict, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [111]:
def print_score(clf, X_train, y_train, X_test, y_test, train=True):
    if train:
        print("Train Result:\n")
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_train, clf.predict(X_train))))
        print("Classification Report: \n {}\n".format(classification_report(y_train, clf.predict(X_train))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_train, clf.predict(X_train))))

        res = cross_val_score(clf, X_train, y_train, cv=10, scoring='accuracy')
        print("Average Accuracy: \t {0:.4f}".format(np.mean(res)))
        print("Accuracy SD: \t\t {0:.4f}".format(np.std(res)))
        print("train auc_roc",roc_auc_score(y_train, clf.predict(X_train)))
    elif train==False:
        print("Test Result:\n")        
        print("accuracy score: {0:.4f}\n".format(accuracy_score(y_test, clf.predict(X_test))))
        print("Classification Report: \n {}\n".format(classification_report(y_test, clf.predict(X_test))))
        print("Confusion Matrix: \n {}\n".format(confusion_matrix(y_test, clf.predict(X_test)))) 
        print("test auc_roc",roc_auc_score(y_test, clf.predict(X_test)))

In [104]:
# simple evaluation on training data
pred_labels = model.predict(training_features)
actual_labels = np.array(outcome_labels['renewal'])

# evaluate model performance
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,roc_curve,roc_auc_score

print('Accuracy:', float(accuracy_score(actual_labels, pred_labels))*100, '%')
print('Classification Stats:')
print(classification_report(actual_labels, pred_labels))
print('hi')
print(roc_curve(actual_labels, pred_labels))
print(roc_auc_score(actual_labels, pred_labels))

Accuracy: 93.74099908582019 %
Classification Stats:
             precision    recall  f1-score   support

          0       0.00      0.00      0.00      4998
          1       0.94      1.00      0.97     74855

avg / total       0.88      0.94      0.91     79853

hi
(array([0., 1.]), array([0., 1.]), array([2, 1]))
0.5


/home/ubuntu/virtualenvironmentpython3/djangovijai/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [64]:
# from sklearn.externals import joblib
# import os
# # save models to be deployed on your server
# if not os.path.exists('Model'):
#     os.mkdir('Model')  
# joblib.dump(model, r'Model/model.pickle')

['Model/model.pickle']

In [65]:
# # load model and scaler objects
# model = joblib.load(r'Model/model.pickle')

In [66]:
test = pd.read_csv('test_1.csv')
#hour_df = pd.read_csv('test_66516Ee.csv')
print("Shape of dataset::{}".format(test.shape))
#Shape of dataset::(79853, 13)

prediction_features = test[feature_names]

Shape of dataset::(34224, 17)


In [67]:
test.isnull().sum()

id                                  0
perc_premium_paid_by_cash_credit    0
age_in_days                         0
Income                              0
Count_3-6_months_late               0
Count_6-12_months_late              0
Count_more_than_12_months_late      0
application_underwriting_score      0
no_of_premiums_paid                 0
premium                             0
sourcing_channel_A                  0
sourcing_channel_B                  0
sourcing_channel_C                  0
sourcing_channel_D                  0
sourcing_channel_E                  0
residence_area_type_Rural           0
residence_area_type_Urban           0
dtype: int64

In [82]:
## predict using model
predictions = model.predict(prediction_features)

## display results
test['renewal'] = predictions
test.head()

id  perc_premium_paid_by_cash_credit  age_in_days    Income  \
0    649                             0.001     0.701181  0.001239   
1  81136                             0.124     0.571388  0.011928   
2  70762                             1.000     0.337874  0.007400   
3  53935                             0.198     0.298677  0.004546   
4  15476                             0.041     0.103863  0.008040   

   Count_3-6_months_late  Count_6-12_months_late  \
0                      0                       0   
1                      0                       0   
2                      0                       0   
3                      0                       0   
4                      1                       0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                               0                        1.000000   
1                               0                        0.879850   
2                               0                        0.896358   
3                               0                        0.888611   
4                               0                        0.909887   

   no_of_premiums_paid   premium  sourcing_channel_A  sourcing_channel_B  \
0             0.087719  0.035714                   1                   0   
1             0.298246  0.178571                   1                   0   
2             0.000000  0.178571                   0                   1   
3             0.157895  0.071429                   0                   1   
4             0.210526  0.142857                   1                   0   

   sourcing_channel_C  sourcing_channel_D  sourcing_channel_E  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   residence_area_type_Rural  residence_area_type_Urban  renewal  renewal_1  
0                          1                          0        1   0.990489  
1                          0                          1        1   0.979421  
2                          0                          1        1   0.911154  
3                          1                          0        1   0.970705  
4                          1                          0        1   0.957531

In [83]:
## predict using model
predictions = model.predict_proba(prediction_features)

## display results
test['renewal_1'] =[el[1] for el in predictions]
test.head()

id  perc_premium_paid_by_cash_credit  age_in_days    Income  \
0    649                             0.001     0.701181  0.001239   
1  81136                             0.124     0.571388  0.011928   
2  70762                             1.000     0.337874  0.007400   
3  53935                             0.198     0.298677  0.004546   
4  15476                             0.041     0.103863  0.008040   

   Count_3-6_months_late  Count_6-12_months_late  \
0                      0                       0   
1                      0                       0   
2                      0                       0   
3                      0                       0   
4                      1                       0   

   Count_more_than_12_months_late  application_underwriting_score  \
0                               0                        1.000000   
1                               0                        0.879850   
2                               0                        0.896358   
3                               0                        0.888611   
4                               0                        0.909887   

   no_of_premiums_paid   premium  sourcing_channel_A  sourcing_channel_B  \
0             0.087719  0.035714                   1                   0   
1             0.298246  0.178571                   1                   0   
2             0.000000  0.178571                   0                   1   
3             0.157895  0.071429                   0                   1   
4             0.210526  0.142857                   1                   0   

   sourcing_channel_C  sourcing_channel_D  sourcing_channel_E  \
0                   0                   0                   0   
1                   0                   0                   0   
2                   0                   0                   0   
3                   0                   0                   0   
4                   0                   0                   0   

   residence_area_type_Rural  residence_area_type_Urban  renewal  renewal_1  
0                          1                          0        1   0.963836  
1                          0                          1        1   0.965178  
2                          0                          1        1   0.907366  
3                          1                          0        1   0.958099  
4                          1                          0        1   0.936448

In [74]:
predictions

array([[0.00951066, 0.99048934],
       [0.02057894, 0.97942106],
       [0.08884578, 0.91115422],
       ...,
       [0.03941027, 0.96058973],
       [0.25025694, 0.74974306],
       [0.02493186, 0.97506814]])

In [69]:
test['renewal'].value_counts()

1    33762
0      462
Name: renewal, dtype: int64

In [78]:
test.to_csv("test_1a.csv",index=None) #93.9476